version: "3.8"

services:
  java_app:
    build:
      context: .
    container_name: "expensesapp"
    environment:
      SPRING_DATABASE_USERNAME: root
      SPRING_DATABASE_PASSWORD: Test@123
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
    ports:
      - "8080:8080"
    #healthcheck:
     # test: ["CMD SHEEL","curl -f http://localhost:8080 || exit 1"]
      #interval: 10s
      #timeout: 5s
     # retries: 5
      #start_period: 30s
    restart: always
    depends_on:
      - mysql_db  
    networks:
      - expenses-app
  mysql_db:
    image: mysql
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - expenses-app
networks:
  expenses-app:  
